services:
  pulse-bot:
    build: .
    container_name: pulse_bot_container
    restart: always
    env_file:
      - .env
    volumes:
      - .:/app
      - ./data:/app/data
      - ./locales:/app/locales
    environment:
      - PYTHONUNBUFFERED=1