"""added language to summary

Revision ID: cfda73a740f7
Revises: f39e9be60657
Create Date: 2026-05-04 20:31:17.044334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfda73a740f7'
down_revision: Union[str, Sequence[str], None] = 'f39e9be60657'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('summaries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(length=10), server_default='en', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('summaries', schema=None) as batch_op:
        batch_op.drop_column('language')

    # ### end Alembic commands ###
