"""added ui language column

Revision ID: f39e9be60657
Revises: 16131a1ebeeb
Create Date: 2026-04-25 10:09:58.289162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f39e9be60657'
down_revision: Union[str, Sequence[str], None] = '16131a1ebeeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tg_language', sa.String(), server_default='en', nullable=False))
        batch_op.add_column(sa.Column('ui_language', sa.String(), server_default='en', nullable=False))
        batch_op.drop_column('language')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.VARCHAR(), server_default='en', nullable=False))
        batch_op.drop_column('ui_language')
        batch_op.drop_column('tg_language')

    # ### end Alembic commands ###
